services:
  raview-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000/api/v1}
        VITE_EUR_TO_RON: ${VITE_EUR_TO_RON:-5}
    image: raview-e-commerce-frontend:latest
    container_name: raview-frontend
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:80"
